[package]
name = "kiwad_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
binary_modifier = "0.3.3"
ctrlc = "3.4.1"
flate2 = "1.0.28"
rayon = "1.8.0"
